# Generated by Django 4.0.5 on 2022-06-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_cellule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cellule',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
